// ShadowSSDTDlg.cpp : implementation file
//

#include "stdafx.h"
#include "MyTaskmgr.h"
#include "ShadowSSDTDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CShadowSSDTDlg dialog


CShadowSSDTDlg::CShadowSSDTDlg(CWnd* pParent /*=NULL*/)
	: CDialog(CShadowSSDTDlg::IDD, pParent)
{
	//{{AFX_DATA_INIT(CShadowSSDTDlg)
		// NOTE: the ClassWizard will add member initialization here
	//}}AFX_DATA_INIT
}


void CShadowSSDTDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CShadowSSDTDlg)
	DDX_Control(pDX, LST_SHADOW, m_LstShadow);
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(CShadowSSDTDlg, CDialog)
	//{{AFX_MSG_MAP(CShadowSSDTDlg)
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CShadowSSDTDlg message handlers

BOOL CShadowSSDTDlg::OnInitDialog() 
{
	CDialog::OnInitDialog();
	
	// TODO: Add extra initialization here
    //设置ListCtrl风格
    m_LstShadow.SetExtendedStyle(m_LstShadow.GetExtendedStyle() |
                                LVS_EX_GRIDLINES |
                                LVS_EX_FULLROWSELECT);
    //设置ListCtrl列名
    m_LstShadow.InsertColumn(1, "序号", LVCFMT_LEFT, 60);
    m_LstShadow.InsertColumn(2, "函数名称", LVCFMT_LEFT, 100);
    m_LstShadow.InsertColumn(3, "当前函数地址", LVCFMT_LEFT, 200);
    m_LstShadow.InsertColumn(4, "Hook", LVCFMT_LEFT, 100);
    m_LstShadow.InsertColumn(5, "原始函数地址", LVCFMT_LEFT, 200);
    m_LstShadow.InsertColumn(6, "当前函数所在模块", LVCFMT_LEFT, 200);
    
    UpdateData(FALSE);
    
    GetShadowSSDTFromSys();
	
	return TRUE;  // return TRUE unless you set the focus to a control
	              // EXCEPTION: OCX Property Pages should return FALSE
}

DWORD CShadowSSDTDlg::GetShadowSSDTFromSys()
{
    char szBuf[MAXBYTE] = {0};
    DWORD dwShadowNum = 0;
    DWORD dwBytes = 0;
    
    extern CMyTaskmgrApp theApp;
    
    HANDLE hDrvFile = theApp.m_hDrvFile;
    if (!DeviceIoControl(hDrvFile, 
                        IOCTRL_GET_SHADOWNUM, 
                        (LPVOID)&dwShadowNum, 
                        sizeof(DWORD),
                        (LPVOID)&dwShadowNum,
                        sizeof(DWORD),
                        &dwBytes, 
                        NULL))
    {
        //CloseHandle(hDrvFile);
        wsprintf(szBuf, "DeviceIoControl IOCTRL_GET_IDTLIMIT ErrorCode:%d\n", GetLastError());
        AfxMessageBox(szBuf);
        return 0;
    }
    DWORD dwShadowSize = dwShadowNum * sizeof(DWORD);
    char *pParams = new char[dwShadowSize];
    if (pParams == NULL)
    {
        wsprintf(szBuf, "new CONTORL_PARAMS faild!");
        AfxMessageBox(szBuf);
        return FALSE;
    }
    ZeroMemory(pParams, dwShadowSize);
    
    if (!DeviceIoControl(hDrvFile, 
                        IOCTRL_GET_SHADOW, 
                        pParams, 
                        dwShadowSize,
                        pParams, 
                        dwShadowSize, 
                        &dwBytes, 
                        NULL))
    {
        //CloseHandle(hDrvFile);
        wsprintf(szBuf, "DeviceIoControl IOCTRL_GET_IDT ErrorCode:%d\n", GetLastError());
        AfxMessageBox(szBuf);
        
        if (pParams != NULL)
        {
            delete pParams;
            pParams = NULL;
        }
        return 0;
    }
    
    char szTmpBuf[MAXBYTE] = {0};
    int j = 0;
    WORD wAttrib = 0;
    DWORD dwSelector = 0;
    DWORD dwOffset = 0;
    DWORD dwP = 0;
    UCHAR chType = 0;
    //解析后填充到ListCtrl
    for (DWORD i = 0; i < dwShadowNum; i++)
    {        
        wsprintf(szTmpBuf, "%d", i);
        m_LstShadow.InsertItem(i, szTmpBuf); //序号
        
        wsprintf(szTmpBuf, "%s", g_szShadowSSDTFuncName[i]);
        m_LstShadow.SetItemText(i, 1, szTmpBuf); //函数名称
        
        wsprintf(szTmpBuf, "0x%08X", ((DWORD *)pParams)[i]);
        m_LstShadow.SetItemText(i, 2, szTmpBuf); //当前函数地址
        
        wsprintf(szTmpBuf, "%s", "-");
        m_LstShadow.SetItemText(i, 3, szTmpBuf); //Hook
        
        wsprintf(szTmpBuf, "0x%08X", ((DWORD *)pParams)[i]);
        m_LstShadow.SetItemText(i, 4, szTmpBuf); //原始函数地址;
        
        wsprintf(szTmpBuf, "%s", "win32k.sys");
        m_LstShadow.SetItemText(i, 5, szTmpBuf); //当前函数地址所在模块;
        
        j++;
    }
    
    if (pParams != NULL)
    {
        delete pParams;
        pParams = NULL;
    }
    
    return TRUE;
}

char *g_szShadowSSDTFuncName[] = {
    "NtGdiAbortDoc",
    "NtGdiAbortPath",
    "NtGdiAddFontResourceW",
    "NtGdiAddRemoteFontToDC",
    "NtGdiAddFontMemResourceEx",
    "NtGdiRemoveMergeFont",
    "NtGdiAddRemoteMMInstanceToDC",
    "NtGdiAlphaBlend",
    "NtGdiAngleArc",
    "NtGdiAnyLinkedFonts",
    "NtGdiFontIsLinked",
    "NtGdiArcInternal",
    "NtGdiBeginPath",
    "NtGdiBitBlt",
    "NtGdiCancelDC",
    "NtGdiCheckBitmapBits",
    "NtGdiCloseFigure",
    "NtGdiClearBitmapAttributes",
    "NtGdiClearBrushAttributes",
    "NtGdiColorCorrectPalette",
    "NtGdiCombineRgn",
    "NtGdiCombineTransform",
    "NtGdiComputeXformCoefficients",
    "NtGdiConsoleTextOut",
    "NtGdiConvertMetafileRect",
    "NtGdiCreateBitmap",
    "NtGdiCreateClientObj",
    "NtGdiCreateColorSpace",
    "NtGdiCreateColorTransform",
    "NtGdiCreateCompatibleBitmap",
    "NtGdiCreateCompatibleDC",
    "NtGdiCreateDIBBrush",
    "NtGdiCreateDIBitmapInternal",
    "NtGdiCreateDIBSection",
    "NtGdiCreateEllipticRgn",
    "NtGdiCreateHalftonePalette",
    "NtGdiCreateHatchBrushInternal",
    "NtGdiCreateMetafileDC",
    "NtGdiCreatePaletteInternal",
    "NtGdiCreatePatternBrushInternal",
    "NtGdiCreatePen",
    "NtGdiCreateRectRgn",
    "NtGdiCreateRoundRectRgn",
    "NtGdiCreateServerMetaFile",
    "NtGdiCreateSolidBrush",
    "NtGdiD3dContextCreate",
    "NtGdiD3dContextDestroy",
    "NtGdiD3dContextDestroyAll",
    "NtGdiD3dValidateTextureStageState",
    "NtGdiD3dDrawPrimitives2",
    "NtGdiDdGetDriverState",
    "NtGdiDdAddAttachedSurface",
    "NtGdiDdAlphaBlt",
    "NtGdiDdAttachSurface",
    "NtGdiDdBeginMoCompFrame",
    "NtGdiDdBlt",
    "NtGdiDdCanCreateSurface",
    "NtGdiDdCanCreateD3DBuffer",
    "NtGdiDdColorControl",
    "NtGdiDdCreateDirectDrawObject",
    "NtGdiDdCreateSurface",
    "NtGdiDdCreateD3DBuffer",
    "NtGdiDdCreateMoComp",
    "NtGdiDdCreateSurfaceObject",
    "NtGdiDdDeleteDirectDrawObject",
    "NtGdiDdDeleteSurfaceObject",
    "NtGdiDdDestroyMoComp",
    "NtGdiDdDestroySurface",
    "NtGdiDdDestroyD3DBuffer",
    "NtGdiDdEndMoCompFrame",
    "NtGdiDdFlip",
    "NtGdiDdFlipToGDISurface",
    "NtGdiDdGetAvailDriverMemory",
    "NtGdiDdGetBltStatus",
    "NtGdiDdGetDC",
    "NtGdiDdGetDriverInfo",
    "NtGdiDdGetDxHandle",
    "NtGdiDdGetFlipStatus",
    "NtGdiDdGetInternalMoCompInfo",
    "NtGdiDdGetMoCompBuffInfo",
    "NtGdiDdGetMoCompGuids",
    "NtGdiDdGetMoCompFormats",
    "NtGdiDdGetScanLine",
    "NtGdiDdLock",
    "NtGdiDdLockD3D",
    "NtGdiDdQueryDirectDrawObject",
    "NtGdiDdQueryMoCompStatus",
    "NtGdiDdReenableDirectDrawObject",
    "NtGdiDdReleaseDC",
    "NtGdiDdRenderMoComp",
    "NtGdiDdResetVisrgn",
    "NtGdiDdSetColorKey",
    "NtGdiDdSetExclusiveMode",
    "NtGdiDdSetGammaRamp",
    "NtGdiDdCreateSurfaceEx",
    "NtGdiDdSetOverlayPosition",
    "NtGdiDdUnattachSurface",
    "NtGdiDdUnlock",
    "NtGdiDdUnlockD3D",
    "NtGdiDdUpdateOverlay",
    "NtGdiDdWaitForVerticalBlank",
    "NtGdiDvpCanCreateVideoPort",
    "NtGdiDvpColorControl",
    "NtGdiDvpCreateVideoPort",
    "NtGdiDvpDestroyVideoPort",
    "NtGdiDvpFlipVideoPort",
    "NtGdiDvpGetVideoPortBandwidth",
    "NtGdiDvpGetVideoPortField",
    "NtGdiDvpGetVideoPortFlipStatus",
    "NtGdiDvpGetVideoPortInputFormats",
    "NtGdiDvpGetVideoPortLine",
    "NtGdiDvpGetVideoPortOutputFormats",
    "NtGdiDvpGetVideoPortConnectInfo",
    "NtGdiDvpGetVideoSignalStatus",
    "NtGdiDvpUpdateVideoPort",
    "NtGdiDvpWaitForVideoPortSync",
    "NtGdiDvpAcquireNotification",
    "NtGdiDvpReleaseNotification",
    "NtGdiDxgGenericThunk",
    "NtGdiDeleteClientObj",
    "NtGdiDeleteColorSpace",
    "NtGdiDeleteColorTransform",
    "NtGdiDeleteObjectApp",
    "NtGdiDescribePixelFormat",
    "NtGdiGetPerBandInfo",
    "NtGdiDoBanding",
    "NtGdiDoPalette",
    "NtGdiDrawEscape",
    "NtGdiEllipse",
    "NtGdiEnableEudc",
    "NtGdiEndDoc",
    "NtGdiEndPage",
    "NtGdiEndPath",
    "NtGdiEnumFontChunk",
    "NtGdiEnumFontClose",
    "NtGdiEnumFontOpen",
    "NtGdiEnumObjects",
    "NtGdiEqualRgn",
    "NtGdiEudcLoadUnloadLink",
    "NtGdiExcludeClipRect",
    "NtGdiExtCreatePen",
    "NtGdiExtCreateRegion",
    "NtGdiExtEscape",
    "NtGdiExtFloodFill",
    "NtGdiExtGetObjectW",
    "NtGdiExtSelectClipRgn",
    "NtGdiExtTextOutW",
    "NtGdiFillPath",
    "NtGdiFillRgn",
    "NtGdiFlattenPath",
    "NtGdiFlushUserBatch",
    "NtGdiFlush",
    "NtGdiForceUFIMapping",
    "NtGdiFrameRgn",
    "NtGdiFullscreenControl",
    "NtGdiGetAndSetDCDword",
    "NtGdiGetAppClipBox",
    "NtGdiGetBitmapBits",
    "NtGdiGetBitmapDimension",
    "NtGdiGetBoundsRect",
    "NtGdiGetCharABCWidthsW",
    "NtGdiGetCharacterPlacementW",
    "NtGdiGetCharSet",
    "NtGdiGetCharWidthW",
    "NtGdiGetCharWidthInfo",
    "NtGdiGetColorAdjustment",
    "NtGdiGetColorSpaceforBitmap",
    "NtGdiGetDCDword",
    "NtGdiGetDCforBitmap",
    "NtGdiGetDCObject",
    "NtGdiGetDCPoint",
    "NtGdiGetDeviceCaps",
    "NtGdiGetDeviceGammaRamp",
    "NtGdiGetDeviceCapsAll",
    "NtGdiGetDIBitsInternal",
    "NtGdiGetETM",
    "NtGdiGetEudcTimeStampEx",
    "NtGdiGetFontData",
    "NtGdiGetFontResourceInfoInternalW",
    "NtGdiGetGlyphIndicesW",
    "NtGdiGetGlyphIndicesWInternal",
    "NtGdiGetGlyphOutline",
    "NtGdiGetKerningPairs",
    "NtGdiGetLinkedUFIs",
    "NtGdiGetMiterLimit",
    "NtGdiGetMonitorID",
    "NtGdiGetNearestColor",
    "NtGdiGetNearestPaletteIndex",
    "NtGdiGetObjectBitmapHandle",
    "NtGdiGetOutlineTextMetricsInternalW",
    "NtGdiGetPath",
    "NtGdiGetPixel",
    "NtGdiGetRandomRgn",
    "NtGdiGetRasterizerCaps",
    "NtGdiGetRealizationInfo",
    "NtGdiGetRegionData",
    "NtGdiGetRgnBox",
    "NtGdiGetServerMetaFileBits",
    "NtGdiGetSpoolMessage",
    "NtGdiGetStats",
    "NtGdiGetStockObject",
    "NtGdiGetStringBitmapW",
    "NtGdiGetSystemPaletteUse",
    "NtGdiGetTextCharsetInfo",
    "NtGdiGetTextExtent",
    "NtGdiGetTextExtentExW",
    "NtGdiGetTextFaceW",
    "NtGdiGetTextMetricsW",
    "NtGdiGetTransform",
    "NtGdiGetUFI",
    "NtGdiGetEmbUFI",
    "NtGdiGetUFIPathname",
    "NtGdiGetEmbedFonts",
    "NtGdiChangeGhostFont",
    "NtGdiAddEmbFontToDC",
    "NtGdiGetFontUnicodeRanges",
    "NtGdiGetWidthTable",
    "NtGdiGradientFill",
    "NtGdiHfontCreate",
    "NtGdiIcmBrushInfo",
    "NtGdiInit",
    "NtGdiInitSpool",
    "NtGdiIntersectClipRect",
    "NtGdiInvertRgn",
    "NtGdiLineTo",
    "NtGdiMakeFontDir",
    "NtGdiMakeInfoDC",
    "NtGdiMaskBlt",
    "NtGdiModifyWorldTransform",
    "NtGdiMonoBitmap",
    "NtGdiMoveTo",
    "NtGdiOffsetClipRgn",
    "NtGdiOffsetRgn",
    "NtGdiOpenDCW",
    "NtGdiPatBlt",
    "NtGdiPolyPatBlt",
    "NtGdiPathToRegion",
    "NtGdiPlgBlt",
    "NtGdiPolyDraw",
    "NtGdiPolyPolyDraw",
    "NtGdiPolyTextOutW",
    "NtGdiPtInRegion",
    "NtGdiPtVisible",
    "NtGdiQueryFonts",
    "NtGdiQueryFontAssocInfo",
    "NtGdiRectangle",
    "NtGdiRectInRegion",
    "NtGdiRectVisible",
    "NtGdiRemoveFontResourceW",
    "NtGdiRemoveFontMemResourceEx",
    "NtGdiResetDC",
    "NtGdiResizePalette",
    "NtGdiRestoreDC",
    "NtGdiRoundRect",
    "NtGdiSaveDC",
    "NtGdiScaleViewportExtEx",
    "NtGdiScaleWindowExtEx",
    "NtGdiSelectBitmap",
    "NtGdiSelectBrush",
    "NtGdiSelectClipPath",
    "NtGdiSelectFont",
    "NtGdiSelectPen",
    "NtGdiSetBitmapAttributes",
    "NtGdiSetBitmapBits",
    "NtGdiSetBitmapDimension",
    "NtGdiSetBoundsRect",
    "NtGdiSetBrushAttributes",
    "NtGdiSetBrushOrg",
    "NtGdiSetColorAdjustment",
    "NtGdiSetColorSpace",
    "NtGdiSetDeviceGammaRamp",
    "NtGdiSetDIBitsToDeviceInternal",
    "NtGdiSetFontEnumeration",
    "NtGdiSetFontXform",
    "NtGdiSetIcmMode",
    "NtGdiSetLinkedUFIs",
    "NtGdiSetMagicColors",
    "NtGdiSetMetaRgn",
    "NtGdiSetMiterLimit",
    "NtGdiGetDeviceWidth",
    "NtGdiMirrorWindowOrg",
    "NtGdiSetLayout",
    "NtGdiSetPixel",
    "NtGdiSetPixelFormat",
    "NtGdiSetRectRgn",
    "NtGdiSetSystemPaletteUse",
    "NtGdiSetTextJustification",
    "NtGdiSetupPublicCFONT",
    "NtGdiSetVirtualResolution",
    "NtGdiSetSizeDevice",
    "NtGdiStartDoc",
    "NtGdiStartPage",
    "NtGdiStretchBlt",
    "NtGdiStretchDIBitsInternal",
    "NtGdiStrokeAndFillPath",
    "NtGdiStrokePath",
    "NtGdiSwapBuffers",
    "NtGdiTransformPoints",
    "NtGdiTransparentBlt",
    "NtGdiUnloadPrinterDriver",
    "NtGdiUnmapMemFont",
    "NtGdiUnrealizeObject",
    "NtGdiUpdateColors",
    "NtGdiWidenPath",
    "NtUserActivateKeyboardLayout",
    "NtUserAlterWindowStyle",
    "NtUserAssociateInputContext",
    "NtUserAttachThreadInput",
    "NtUserBeginPaint",
    "NtUserBitBltSysBmp",
    "NtUserBlockInput",
    "NtUserBuildHimcList",
    "NtUserBuildHwndList",
    "NtUserBuildNameList",
    "NtUserBuildPropList",
    "NtUserCallHwnd",
    "NtUserCallHwndLock",
    "NtUserCallHwndOpt",
    "NtUserCallHwndParam",
    "NtUserCallHwndParamLock",
    "NtUserCallMsgFilter",
    "NtUserCallNextHookEx",
    "NtUserCallNoParam",
    "NtUserCallOneParam",
    "NtUserCallTwoParam",
    "NtUserChangeClipboardChain",
    "NtUserChangeDisplaySettings",
    "NtUserCheckImeHotKey",
    "NtUserCheckMenuItem",
    "NtUserChildWindowFromPointEx",
    "NtUserClipCursor",
    "NtUserCloseClipboard",
    "NtUserCloseDesktop",
    "NtUserCloseWindowStation",
    "NtUserConsoleControl",
    "NtUserConvertMemHandle",
    "NtUserCopyAcceleratorTable",
    "NtUserCountClipboardFormats",
    "NtUserCreateAcceleratorTable",
    "NtUserCreateCaret",
    "NtUserCreateDesktop",
    "NtUserCreateInputContext",
    "NtUserCreateLocalMemHandle",
    "NtUserCreateWindowEx",
    "NtUserCreateWindowStation",
    "NtUserDdeGetQualityOfService",
    "NtUserDdeInitialize",
    "NtUserDdeSetQualityOfService",
    "NtUserDeferWindowPos",
    "NtUserDefSetText",
    "NtUserDeleteMenu",
    "NtUserDestroyAcceleratorTable",
    "NtUserDestroyCursor",
    "NtUserDestroyInputContext",
    "NtUserDestroyMenu",
    "NtUserDestroyWindow",
    "NtUserDisableThreadIme",
    "NtUserDispatchMessage",
    "NtUserDragDetect",
    "NtUserDragObject",
    "NtUserDrawAnimatedRects",
    "NtUserDrawCaption",
    "NtUserDrawCaptionTemp",
    "NtUserDrawIconEx",
    "NtUserDrawMenuBarTemp",
    "NtUserEmptyClipboard",
    "NtUserEnableMenuItem",
    "NtUserEnableScrollBar",
    "NtUserEndDeferWindowPosEx",
    "NtUserEndMenu",
    "NtUserEndPaint",
    "NtUserEnumDisplayDevices",
    "NtUserEnumDisplayMonitors",
    "NtUserEnumDisplaySettings",
    "NtUserEvent",
    "NtUserExcludeUpdateRgn",
    "NtUserFillWindow",
    "NtUserFindExistingCursorIcon",
    "NtUserFindWindowEx",
    "NtUserFlashWindowEx",
    "NtUserGetAltTabInfo",
    "NtUserGetAncestor",
    "NtUserGetAppImeLevel",
    "NtUserGetAsyncKeyState",
    "NtUserGetAtomName",
    "NtUserGetCaretBlinkTime",
    "NtUserGetCaretPos",
    "NtUserGetClassInfo",
    "NtUserGetClassName",
    "NtUserGetClipboardData",
    "NtUserGetClipboardFormatName",
    "NtUserGetClipboardOwner",
    "NtUserGetClipboardSequenceNumber",
    "NtUserGetClipboardViewer",
    "NtUserGetClipCursor",
    "NtUserGetComboBoxInfo",
    "NtUserGetControlBrush",
    "NtUserGetControlColor",
    "NtUserGetCPD",
    "NtUserGetCursorFrameInfo",
    "NtUserGetCursorInfo",
    "NtUserGetDC",
    "NtUserGetDCEx",
    "NtUserGetDoubleClickTime",
    "NtUserGetForegroundWindow",
    "NtUserGetGuiResources",
    "NtUserGetGUIThreadInfo",
    "NtUserGetIconInfo",
    "NtUserGetIconSize",
    "NtUserGetImeHotKey",
    "NtUserGetImeInfoEx",
    "NtUserGetInternalWindowPos",
    "NtUserGetKeyboardLayoutList",
    "NtUserGetKeyboardLayoutName",
    "NtUserGetKeyboardState",
    "NtUserGetKeyNameText",
    "NtUserGetKeyState",
    "NtUserGetListBoxInfo",
    "NtUserGetMenuBarInfo",
    "NtUserGetMenuIndex",
    "NtUserGetMenuItemRect",
    "NtUserGetMessage",
    "NtUserGetMouseMovePointsEx",
    "NtUserGetObjectInformation",
    "NtUserGetOpenClipboardWindow",
    "NtUserGetPriorityClipboardFormat",
    "NtUserGetProcessWindowStation",
    "NtUserGetRawInputBuffer",
    "NtUserGetRawInputData",
    "NtUserGetRawInputDeviceInfo",
    "NtUserGetRawInputDeviceList",
    "NtUserGetRegisteredRawInputDevices",
    "NtUserGetScrollBarInfo",
    "NtUserGetSystemMenu",
    "NtUserGetThreadDesktop",
    "NtUserGetThreadState",
    "NtUserGetTitleBarInfo",
    "NtUserGetUpdateRect",
    "NtUserGetUpdateRgn",
    "NtUserGetWindowDC",
    "NtUserGetWindowPlacement",
    "NtUserGetWOWClass",
    "NtUserHardErrorControl",
    "NtUserHideCaret",
    "NtUserHiliteMenuItem",
    "NtUserImpersonateDdeClientWindow",
    "NtUserInitialize",
    "NtUserInitializeClientPfnArrays",
    "NtUserInitTask",
    "NtUserInternalGetWindowText",
    "NtUserInvalidateRect",
    "NtUserInvalidateRgn",
    "NtUserIsClipboardFormatAvailable",
    "NtUserKillTimer",
    "NtUserLoadKeyboardLayoutEx",
    "NtUserLockWindowStation",
    "NtUserLockWindowUpdate",
    "NtUserLockWorkStation",
    "NtUserMapVirtualKeyEx",
    "NtUserMenuItemFromPoint",
    "NtUserMessageCall",
    "NtUserMinMaximize",
    "NtUserMNDragLeave",
    "NtUserMNDragOver",
    "NtUserModifyUserStartupInfoFlags",
    "NtUserMoveWindow",
    "NtUserNotifyIMEStatus",
    "NtUserNotifyProcessCreate",
    "NtUserNotifyWinEvent",
    "NtUserOpenClipboard",
    "NtUserOpenDesktop",
    "NtUserOpenInputDesktop",
    "NtUserOpenWindowStation",
    "NtUserPaintDesktop",
    "NtUserPeekMessage",
    "NtUserPostMessage",
    "NtUserPostThreadMessage",
    "NtUserPrintWindow",
    "NtUserProcessConnect",
    "NtUserQueryInformationThread",
    "NtUserQueryInputContext",
    "NtUserQuerySendMessage",
    "NtUserQueryUserCounters",
    "NtUserQueryWindow",
    "NtUserRealChildWindowFromPoint",
    "NtUserRealInternalGetMessage",
    "NtUserRealWaitMessageEx",
    "NtUserRedrawWindow",
    "NtUserRegisterClassExWOW",
    "NtUserRegisterUserApiHook",
    "NtUserRegisterHotKey",
    "NtUserRegisterRawInputDevices",
    "NtUserRegisterTasklist",
    "NtUserRegisterWindowMessage",
    "NtUserRemoveMenu",
    "NtUserRemoveProp",
    "NtUserResolveDesktop",
    "NtUserResolveDesktopForWOW",
    "NtUserSBGetParms",
    "NtUserScrollDC",
    "NtUserScrollWindowEx",
    "NtUserSelectPalette",
    "NtUserSendInput",
    "NtUserSetActiveWindow",
    "NtUserSetAppImeLevel",
    "NtUserSetCapture",
    "NtUserSetClassLong",
    "NtUserSetClassWord",
    "NtUserSetClipboardData",
    "NtUserSetClipboardViewer",
    "NtUserSetConsoleReserveKeys",
    "NtUserSetCursor",
    "NtUserSetCursorContents",
    "NtUserSetCursorIconData",
    "NtUserSetDbgTag",
    "NtUserSetFocus",
    "NtUserSetImeHotKey",
    "NtUserSetImeInfoEx",
    "NtUserSetImeOwnerWindow",
    "NtUserSetInformationProcess",
    "NtUserSetInformationThread",
    "NtUserSetInternalWindowPos",
    "NtUserSetKeyboardState",
    "NtUserSetLogonNotifyWindow",
    "NtUserSetMenu",
    "NtUserSetMenuContextHelpId",
    "NtUserSetMenuDefaultItem",
    "NtUserSetMenuFlagRtoL",
    "NtUserSetObjectInformation",
    "NtUserSetParent",
    "NtUserSetProcessWindowStation",
    "NtUserSetProp",
    "NtUserSetRipFlags",
    "NtUserSetScrollInfo",
    "NtUserSetShellWindowEx",
    "NtUserSetSysColors",
    "NtUserSetSystemCursor",
    "NtUserSetSystemMenu",
    "NtUserSetSystemTimer",
    "NtUserSetThreadDesktop",
    "NtUserSetThreadLayoutHandles",
    "NtUserSetThreadState",
    "NtUserSetTimer",
    "NtUserSetWindowFNID",
    "NtUserSetWindowLong",
    "NtUserSetWindowPlacement",
    "NtUserSetWindowPos",
    "NtUserSetWindowRgn",
    "NtUserSetWindowsHookAW",
    "NtUserSetWindowsHookEx",
    "NtUserSetWindowStationUser",
    "NtUserSetWindowWord",
    "NtUserSetWinEventHook",
    "NtUserShowCaret",
    "NtUserShowScrollBar",
    "NtUserShowWindow",
    "NtUserShowWindowAsync",
    "NtUserSoundSentry",
    "NtUserSwitchDesktop",
    "NtUserSystemParametersInfo",
    "NtUserTestForInteractiveUser",
    "NtUserThunkedMenuInfo",
    "NtUserThunkedMenuItemInfo",
    "NtUserToUnicodeEx",
    "NtUserTrackMouseEvent",
    "NtUserTrackPopupMenuEx",
    "NtUserCalcMenuBar",
    "NtUserPaintMenuBar",
    "NtUserTranslateAccelerator",
    "NtUserTranslateMessage",
    "NtUserUnhookWindowsHookEx",
    "NtUserUnhookWinEvent",
    "NtUserUnloadKeyboardLayout",
    "NtUserUnlockWindowStation",
    "NtUserUnregisterClass",
    "NtUserUnregisterUserApiHook",
    "NtUserUnregisterHotKey",
    "NtUserUpdateInputContext",
    "NtUserUpdateInstance",
    "NtUserUpdateLayeredWindow",
    "NtUserGetLayeredWindowAttributes",
    "NtUserSetLayeredWindowAttributes",
    "NtUserUpdatePerUserSystemParameters",
    "NtUserUserHandleGrantAccess",
    "NtUserValidateHandleSecure",
    "NtUserValidateRect",
    "NtUserValidateTimerCallback",
    "NtUserVkKeyScanEx",
    "NtUserWaitForInputIdle",
    "NtUserWaitForMsgAndEvent",
    "NtUserWaitMessage",
    "NtUserWin32PoolAllocationStats",
    "NtUserWindowFromPoint",
    "NtUserYieldTask",
    "NtUserRemoteConnect",
    "NtUserRemoteRedrawRectangle",
    "NtUserRemoteRedrawScreen",
    "NtUserRemoteStopScreenUpdates",
    "NtUserCtxDisplayIOCtl",
    "NtGdiEngAssociateSurface",
    "NtGdiEngCreateBitmap",
    "NtGdiEngCreateDeviceSurface",
    "NtGdiEngCreateDeviceBitmap",
    "NtGdiEngCreatePalette",
    "NtGdiEngComputeGlyphSet",
    "NtGdiEngCopyBits",
    "NtGdiEngDeletePalette",
    "NtGdiEngDeleteSurface",
    "NtGdiEngEraseSurface",
    "NtGdiEngUnlockSurface",
    "NtGdiEngLockSurface",
    "NtGdiEngBitBlt",
    "NtGdiEngStretchBlt",
    "NtGdiEngPlgBlt",
    "NtGdiEngMarkBandingSurface",
    "NtGdiEngStrokePath",
    "NtGdiEngFillPath",
    "NtGdiEngStrokeAndFillPath",
    "NtGdiEngPaint",
    "NtGdiEngLineTo",
    "NtGdiEngAlphaBlend",
    "NtGdiEngGradientFill",
    "NtGdiEngTransparentBlt",
    "NtGdiEngTextOut",
    "NtGdiEngStretchBltROP",
    "NtGdiXLATEOBJ_cGetPalette",
    "NtGdiXLATEOBJ_iXlate",
    "NtGdiXLATEOBJ_hGetColorTransform",
    "NtGdiCLIPOBJ_bEnum",
    "NtGdiCLIPOBJ_cEnumStart",
    "NtGdiCLIPOBJ_ppoGetPath",
    "NtGdiEngDeletePath",
    "NtGdiEngCreateClip",
    "NtGdiEngDeleteClip",
    "NtGdiBRUSHOBJ_ulGetBrushColor",
    "NtGdiBRUSHOBJ_pvAllocRbrush",
    "NtGdiBRUSHOBJ_pvGetRbrush",
    "NtGdiBRUSHOBJ_hGetColorTransform",
    "NtGdiXFORMOBJ_bApplyXform",
    "NtGdiXFORMOBJ_iGetXform",
    "NtGdiFONTOBJ_vGetInfo",
    "NtGdiFONTOBJ_pxoGetXform",
    "NtGdiFONTOBJ_cGetGlyphs",
    "NtGdiFONTOBJ_pifi",
    "NtGdiFONTOBJ_pfdg",
    "NtGdiFONTOBJ_pQueryGlyphAttrs",
    "NtGdiFONTOBJ_pvTrueTypeFontFile",
    "NtGdiFONTOBJ_cGetAllGlyphHandles",
    "NtGdiSTROBJ_bEnum",
    "NtGdiSTROBJ_bEnumPositionsOnly",
    "NtGdiSTROBJ_bGetAdvanceWidths",
    "NtGdiSTROBJ_vEnumStart",
    "NtGdiSTROBJ_dwGetCodePage",
    "NtGdiPATHOBJ_vGetBounds",
    "NtGdiPATHOBJ_bEnum",
    "NtGdiPATHOBJ_vEnumStart",
    "NtGdiPATHOBJ_vEnumStartClipLines",
    "NtGdiPATHOBJ_bEnumClipLines",
    "NtGdiGetDhpdev",
    "NtGdiEngCheckAbort",
    "NtGdiHT_Get8BPPFormatPalette",
    "NtGdiHT_Get8BPPMaskPalette",
    "NtGdiUpdateTransform",
    "NtGdiSetPUMPDOBJ",
    "NtGdiBRUSHOBJ_DeleteRbrush",
    "NtGdiUnmapMemFont",
    "NtGdiDrawStream"
};
