// ShadowSSDTDlg.cpp : implementation file
//

#include "stdafx.h"
#include "MyTaskmgr.h"
#include "ShadowSSDTDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CShadowSSDTDlg dialog


CShadowSSDTDlg::CShadowSSDTDlg(CWnd* pParent /*=NULL*/)
	: CDialog(CShadowSSDTDlg::IDD, pParent)
{
	//{{AFX_DATA_INIT(CShadowSSDTDlg)
		// NOTE: the ClassWizard will add member initialization here
	//}}AFX_DATA_INIT
}


void CShadowSSDTDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CShadowSSDTDlg)
	DDX_Control(pDX, LST_SHADOW, m_LstShadow);
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(CShadowSSDTDlg, CDialog)
	//{{AFX_MSG_MAP(CShadowSSDTDlg)
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CShadowSSDTDlg message handlers

BOOL CShadowSSDTDlg::OnInitDialog() 
{
	CDialog::OnInitDialog();
	
	// TODO: Add extra initialization here
    //设置ListCtrl风格
    m_LstShadow.SetExtendedStyle(m_LstShadow.GetExtendedStyle() |
                                LVS_EX_GRIDLINES |
                                LVS_EX_FULLROWSELECT);
    //设置ListCtrl列名
    m_LstShadow.InsertColumn(1, "序号", LVCFMT_LEFT, 60);
    m_LstShadow.InsertColumn(2, "函数名称", LVCFMT_LEFT, 100);
    m_LstShadow.InsertColumn(3, "当前函数地址", LVCFMT_LEFT, 200);
    m_LstShadow.InsertColumn(4, "Hook", LVCFMT_LEFT, 100);
    m_LstShadow.InsertColumn(5, "原始函数地址", LVCFMT_LEFT, 200);
    m_LstShadow.InsertColumn(6, "当前函数所在模块", LVCFMT_LEFT, 200);
    
    UpdateData(FALSE);
    
    GetShadowSSDTFromSys();
	
	return TRUE;  // return TRUE unless you set the focus to a control
	              // EXCEPTION: OCX Property Pages should return FALSE
}

DWORD CShadowSSDTDlg::GetShadowSSDTFromSys()
{
    char szBuf[MAXBYTE] = {0};
    DWORD dwShadowNum = 0;
    DWORD dwBytes = 0;
    
    extern CMyTaskmgrApp theApp;
    
    HANDLE hDrvFile = theApp.m_hDrvFile;
//     if (!DeviceIoControl(hDrvFile, 
//                         IOCTRL_GET_SHADOWNUM, 
//                         (LPVOID)&dwShadowNum, 
//                         sizeof(DWORD),
//                         (LPVOID)&dwShadowNum,
//                         sizeof(DWORD),
//                         &dwBytes, 
//                         NULL))
//     {
//         //CloseHandle(hDrvFile);
//         wsprintf(szBuf, "DeviceIoControl IOCTRL_GET_IDTLIMIT ErrorCode:%d\n", GetLastError());
//         AfxMessageBox(szBuf);
//         return 0;
//     }

    dwShadowNum = 827; //不从内核中取了 直接写死
    DWORD dwShadowSize = dwShadowNum * sizeof(ULONGLONG);
    ULONGLONG *pParams = new ULONGLONG[dwShadowNum];
    if (pParams == NULL)
    {
        wsprintf(szBuf, "new CONTORL_PARAMS faild!");
        AfxMessageBox(szBuf);
        return FALSE;
    }
    ZeroMemory(pParams, dwShadowSize);
    
    if (!DeviceIoControl(hDrvFile, 
                        IOCTRL_GET_SHADOW, 
                        pParams, 
                        dwShadowSize,
                        pParams, 
                        dwShadowSize, 
                        &dwBytes, 
                        NULL))
    {
        //CloseHandle(hDrvFile);
        wsprintf(szBuf, "DeviceIoControl IOCTRL_GET_IDT ErrorCode:%d\n", GetLastError());
        AfxMessageBox(szBuf);
        
        if (pParams != NULL)
        {
            delete pParams;
            pParams = NULL;
        }
        return 0;
    }
    
    char szTmpBuf[MAXBYTE] = {0};
    int j = 0;
    WORD wAttrib = 0;
    DWORD dwSelector = 0;
    DWORD dwOffset = 0;
    DWORD dwP = 0;
    UCHAR chType = 0;
    //解析后填充到ListCtrl
    for (DWORD i = 0; i < dwShadowNum; i++)
    {        
        wsprintf(szTmpBuf, "%d", i);
        m_LstShadow.InsertItem(i, szTmpBuf); //序号
        
        wsprintf(szTmpBuf, "%s", g_szShadowSSDTFuncName[i]);
        m_LstShadow.SetItemText(i, 1, szTmpBuf); //函数名称
        
        wsprintf(szTmpBuf, "0xFFFFF96%011X", pParams[i]);
        m_LstShadow.SetItemText(i, 2, szTmpBuf); //当前函数地址
        
        wsprintf(szTmpBuf, "%s", "-");
        m_LstShadow.SetItemText(i, 3, szTmpBuf); //Hook
        
        wsprintf(szTmpBuf, "0xFFFFF96%011X", pParams[i]);
        m_LstShadow.SetItemText(i, 4, szTmpBuf); //原始函数地址;
        
        wsprintf(szTmpBuf, "%s", "C:\\Windows\\System32win32k.sys");
        m_LstShadow.SetItemText(i, 5, szTmpBuf); //当前函数地址所在模块;
        
        j++;
    }
    
    if (pParams != NULL)
    {
        delete pParams;
        pParams = NULL;
    }
    
    return TRUE;
}

char *g_szShadowSSDTFuncName[] = {
   "NtUserGetThreadState",
"NtUserPeekMessage",
"NtUserCallOneParam",
"NtUserGetKeyState",
"NtUserInvalidateRect",
"NtUserCallNoParam",
"NtUserGetMessage",
"NtUserMessageCall",
"NtGdiBitBlt",
"NtGdiGetCharSet",
"NtUserGetDC",
"NtGdiSelectBitmap",
"NtUserWaitMessage",
"NtUserTranslateMessage",
"NtUserGetProp",
"NtUserPostMessage",
"NtUserQueryWindow",
"NtUserTranslateAccelerator",
"NtGdiFlush",
"NtUserRedrawWindow",
"NtUserWindowFromPoint",
"NtUserCallMsgFilter",
"NtUserValidateTimerCallback",
"NtUserBeginPaint",
"NtUserSetTimer",
"NtUserEndPaint",
"NtUserSetCursor",
"NtUserKillTimer",
"NtUserBuildHwndList",
"NtUserSelectPalette",
"NtUserCallNextHookEx",
"NtUserHideCaret",
"NtGdiIntersectClipRect",
"NtUserCallHwndLock",
"NtUserGetProcessWindowStation",
"NtGdiDeleteObjectApp",
"NtUserSetWindowPos",
"NtUserShowCaret",
"NtUserEndDeferWindowPosEx",
"NtUserCallHwndParamLock",
"NtUserVkKeyScanEx",
"NtGdiSetDIBitsToDeviceInternal",
"NtUserCallTwoParam",
"NtGdiGetRandomRgn",
"NtUserCopyAcceleratorTable",
"NtUserNotifyWinEvent",
"NtGdiExtSelectClipRgn",
"NtUserIsClipboardFormatAvailable",
"NtUserSetScrollInfo",
"NtGdiStretchBlt",
"NtUserCreateCaret",
"NtGdiRectVisible",
"NtGdiCombineRgn",
"NtGdiGetDCObject",
"NtUserDispatchMessage",
"NtUserRegisterWindowMessage",
"NtGdiExtTextOutW",
"NtGdiSelectFont",
"NtGdiRestoreDC",
"NtGdiSaveDC",
"NtUserGetForegroundWindow",
"NtUserShowScrollBar",
"NtUserFindExistingCursorIcon",
"NtGdiGetDCDword",
"NtGdiGetRegionData",
"NtGdiLineTo",
"NtUserSystemParametersInfo",
"NtGdiGetAppClipBox",
"NtUserGetAsyncKeyState",
"NtUserGetCPD",
"NtUserRemoveProp",
"NtGdiDoPalette",
"NtGdiPolyPolyDraw",
"NtUserSetCapture",
"NtUserEnumDisplayMonitors",
"NtGdiCreateCompatibleBitmap",
"NtUserSetProp",
"NtGdiGetTextCharsetInfo",
"NtUserSBGetParms",
"NtUserGetIconInfo",
"NtUserExcludeUpdateRgn",
"NtUserSetFocus",
"NtGdiExtGetObjectW",
"NtUserDeferWindowPos",
"NtUserGetUpdateRect",
"NtGdiCreateCompatibleDC",
"NtUserGetClipboardSequenceNumber",
"NtGdiCreatePen",
"NtUserShowWindow",
"NtUserGetKeyboardLayoutList",
"NtGdiPatBlt",
"NtUserMapVirtualKeyEx",
"NtUserSetWindowLong",
"NtGdiHfontCreate",
"NtUserMoveWindow",
"NtUserPostThreadMessage",
"NtUserDrawIconEx",
"NtUserGetSystemMenu",
"NtGdiDrawStream",
"NtUserInternalGetWindowText",
"NtUserGetWindowDC",
"NtGdiD3dDrawPrimitives2",
"NtGdiInvertRgn",
"NtGdiGetRgnBox",
"NtGdiGetAndSetDCDword",
"NtGdiMaskBlt",
"NtGdiGetWidthTable",
"NtUserScrollDC",
"NtUserGetObjectInformation",
"NtGdiCreateBitmap",
"NtUserFindWindowEx",
"NtGdiPolyPatBlt",
"NtUserUnhookWindowsHookEx",
"NtGdiGetNearestColor",
"NtGdiTransformPoints",
"NtGdiGetDCPoint",
"NtGdiCreateDIBBrush",
"NtGdiGetTextMetricsW",
"NtUserCreateWindowEx",
"NtUserSetParent",
"NtUserGetKeyboardState",
"NtUserToUnicodeEx",
"NtUserGetControlBrush",
"NtUserGetClassName",
"NtGdiAlphaBlend",
"NtGdiDdBlt",
"NtGdiOffsetRgn",
"NtUserDefSetText",
"NtGdiGetTextFaceW",
"NtGdiStretchDIBitsInternal",
"NtUserSendInput",
"NtUserGetThreadDesktop",
"NtGdiCreateRectRgn",
"NtGdiGetDIBitsInternal",
"NtUserGetUpdateRgn",
"NtGdiDeleteClientObj",
"NtUserGetIconSize",
"NtUserFillWindow",
"NtGdiExtCreateRegion",
"NtGdiComputeXformCoefficients",
"NtUserSetWindowsHookEx",
"NtUserNotifyProcessCreate",
"NtGdiUnrealizeObject",
"NtUserGetTitleBarInfo",
"NtGdiRectangle",
"NtUserSetThreadDesktop",
"NtUserGetDCEx",
"NtUserGetScrollBarInfo",
"NtGdiGetTextExtent",
"NtUserSetWindowFNID",
"NtGdiSetLayout",
"NtUserCalcMenuBar",
"NtUserThunkedMenuItemInfo",
"NtGdiExcludeClipRect",
"NtGdiCreateDIBSection",
"NtGdiGetDCforBitmap",
"NtUserDestroyCursor",
"NtUserDestroyWindow",
"NtUserCallHwndParam",
"NtGdiCreateDIBitmapInternal",
"NtUserOpenWindowStation",
"NtGdiDdDeleteSurfaceObject",
"NtGdiDdCanCreateSurface",
"NtGdiDdCreateSurface",
"NtUserSetCursorIconData",
"NtGdiDdDestroySurface",
"NtUserCloseDesktop",
"NtUserOpenDesktop",
"NtUserSetProcessWindowStation",
"NtUserGetAtomName",
"NtGdiDdResetVisrgn",
"NtGdiExtCreatePen",
"NtGdiCreatePaletteInternal",
"NtGdiSetBrushOrg",
"NtUserBuildNameList",
"NtGdiSetPixel",
"NtUserRegisterClassExWOW",
"NtGdiCreatePatternBrushInternal",
"NtUserGetAncestor",
"NtGdiGetOutlineTextMetricsInternalW",
"NtGdiSetBitmapBits",
"NtUserCloseWindowStation",
"NtUserGetDoubleClickTime",
"NtUserEnableScrollBar",
"NtGdiCreateSolidBrush",
"NtUserGetClassInfoEx",
"NtGdiCreateClientObj",
"NtUserUnregisterClass",
"NtUserDeleteMenu",
"NtGdiRectInRegion",
"NtUserScrollWindowEx",
"NtGdiGetPixel",
"NtUserSetClassLong",
"NtUserGetMenuBarInfo",
"NtGdiDdCreateSurfaceEx",
"NtGdiDdCreateSurfaceObject",
"NtGdiGetNearestPaletteIndex",
"NtGdiDdLockD3D",
"NtGdiDdUnlockD3D",
"NtGdiGetCharWidthW",
"NtUserInvalidateRgn",
"NtUserGetClipboardOwner",
"NtUserSetWindowRgn",
"NtUserBitBltSysBmp",
"NtGdiGetCharWidthInfo",
"NtUserValidateRect",
"NtUserCloseClipboard",
"NtUserOpenClipboard",
"NtGdiGetStockObject",
"NtUserSetClipboardData",
"NtUserEnableMenuItem",
"NtUserAlterWindowStyle",
"NtGdiFillRgn",
"NtUserGetWindowPlacement",
"NtGdiModifyWorldTransform",
"NtGdiGetFontData",
"NtUserGetOpenClipboardWindow",
"NtUserSetThreadState",
"NtGdiOpenDCW",
"NtUserTrackMouseEvent",
"NtGdiGetTransform",
"NtUserDestroyMenu",
"NtGdiGetBitmapBits",
"NtUserConsoleControl",
"NtUserSetActiveWindow",
"NtUserSetInformationThread",
"NtUserSetWindowPlacement",
"NtUserGetControlColor",
"NtGdiSetMetaRgn",
"NtGdiSetMiterLimit",
"NtGdiSetVirtualResolution",
"NtGdiGetRasterizerCaps",
"NtUserSetWindowWord",
"NtUserGetClipboardFormatName",
"NtUserRealInternalGetMessage",
"NtUserCreateLocalMemHandle",
"NtUserAttachThreadInput",
"NtGdiCreateHalftonePalette",
"NtUserPaintMenuBar",
"NtUserSetKeyboardState",
"NtGdiCombineTransform",
"NtUserCreateAcceleratorTable",
"NtUserGetCursorFrameInfo",
"NtUserGetAltTabInfo",
"NtUserGetCaretBlinkTime",
"NtGdiQueryFontAssocInfo",
"NtUserProcessConnect",
"NtUserEnumDisplayDevices",
"NtUserEmptyClipboard",
"NtUserGetClipboardData",
"NtUserRemoveMenu",
"NtGdiSetBoundsRect",
"NtGdiGetBitmapDimension",
"NtUserConvertMemHandle",
"NtUserDestroyAcceleratorTable",
"NtUserGetGUIThreadInfo",
"NtGdiCloseFigure",
"NtUserSetWindowsHookAW",
"NtUserSetMenuDefaultItem",
"NtUserCheckMenuItem",
"NtUserSetWinEventHook",
"NtUserUnhookWinEvent",
"NtUserLockWindowUpdate",
"NtUserSetSystemMenu",
"NtUserThunkedMenuInfo",
"NtGdiBeginPath",
"NtGdiEndPath",
"NtGdiFillPath",
"NtUserCallHwnd",
"NtUserDdeInitialize",
"NtUserModifyUserStartupInfoFlags",
"NtUserCountClipboardFormats",
"NtGdiAddFontMemResourceEx",
"NtGdiEqualRgn",
"NtGdiGetSystemPaletteUse",
"NtGdiRemoveFontMemResourceEx",
"NtUserEnumDisplaySettings",
"NtUserPaintDesktop",
"NtGdiExtEscape",
"NtGdiSetBitmapDimension",
"NtGdiSetFontEnumeration",
"NtUserChangeClipboardChain",
"NtUserSetClipboardViewer",
"NtUserShowWindowAsync",
"NtGdiCreateColorSpace",
"NtGdiDeleteColorSpace",
"NtUserActivateKeyboardLayout",
"NtGdiAbortDoc",
"NtGdiAbortPath",
"NtGdiAddEmbFontToDC",
"NtGdiAddFontResourceW",
"NtGdiAddRemoteFontToDC",
"NtGdiAddRemoteMMInstanceToDC",
"NtGdiAngleArc",
"NtGdiAnyLinkedFonts",
"NtGdiArcInternal",
"NtGdiBRUSHOBJ_DeleteRbrush",
"NtGdiBRUSHOBJ_hGetColorTransform",
"NtGdiBRUSHOBJ_pvAllocRbrush",
"NtGdiBRUSHOBJ_pvGetRbrush",
"NtGdiBRUSHOBJ_ulGetBrushColor",
"NtGdiBeginGdiRendering",
"NtGdiCLIPOBJ_bEnum",
"NtGdiCLIPOBJ_cEnumStart",
"NtGdiCLIPOBJ_ppoGetPath",
"NtGdiCancelDC",
"NtGdiChangeGhostFont",
"NtGdiCheckBitmapBits",
"NtGdiClearBitmapAttributes",
"NtGdiClearBrushAttributes",
"NtGdiColorCorrectPalette",
"NtGdiConfigureOPMProtectedOutput",
"NtGdiConvertMetafileRect",
"NtGdiCreateBitmapFromDxSurface",
"NtGdiCreateColorTransform",
"NtGdiCreateEllipticRgn",
"NtGdiCreateHatchBrushInternal",
"NtGdiCreateMetafileDC",
"NtGdiCreateOPMProtectedOutputs",
"NtGdiCreateRoundRectRgn",
"NtGdiCreateServerMetaFile",
"NtGdiD3dContextCreate",
"NtGdiD3dContextDestroy",
"NtGdiD3dContextDestroyAll",
"NtGdiD3dValidateTextureStageState",
"NtGdiDDCCIGetCapabilitiesString",
"NtGdiDDCCIGetCapabilitiesStringLength",
"NtGdiDDCCIGetTimingReport",
"NtGdiDDCCIGetVCPFeature",
"NtGdiDDCCISaveCurrentSettings",
"NtGdiDDCCISetVCPFeature",
"NtGdiDdAddAttachedSurface",
"NtGdiDdAlphaBlt",
"NtGdiDdAttachSurface",
"NtGdiDdBeginMoCompFrame",
"NtGdiDdCanCreateD3DBuffer",
"NtGdiDdColorControl",
"NtGdiDdCreateD3DBuffer",
"NtGdiDdCreateDirectDrawObject",
"NtGdiDdCreateFullscreenSprite",
"NtGdiDdCreateMoComp",
"NtGdiDdDDIAcquireKeyedMutex",
"NtGdiDdDDICheckExclusiveOwnership",
"NtGdiDdDDICheckMonitorPowerState",
"NtGdiDdDDICheckOcclusion",
"NtGdiDdDDICheckSharedResourceAccess",
"NtGdiDdDDICheckVidPnExclusiveOwnership",
"NtGdiDdDDICloseAdapter",
"NtGdiDdDDIConfigureSharedResource",
"NtGdiDdDDICreateAllocation",
"NtGdiDdDDICreateContext",
"NtGdiDdDDICreateDCFromMemory",
"NtGdiDdDDICreateDevice",
"NtGdiDdDDICreateKeyedMutex",
"NtGdiDdDDICreateOverlay",
"NtGdiDdDDICreateSynchronizationObject",
"NtGdiDdDDIDestroyAllocation",
"NtGdiDdDDIDestroyContext",
"NtGdiDdDDIDestroyDCFromMemory",
"NtGdiDdDDIDestroyDevice",
"NtGdiDdDDIDestroyKeyedMutex",
"NtGdiDdDDIDestroyOverlay",
"NtGdiDdDDIDestroySynchronizationObject",
"NtGdiDdDDIEscape",
"NtGdiDdDDIFlipOverlay",
"NtGdiDdDDIGetContextSchedulingPriority",
"NtGdiDdDDIGetDeviceState",
"NtGdiDdDDIGetDisplayModeList",
"NtGdiDdDDIGetMultisampleMethodList",
"NtGdiDdDDIGetOverlayState",
"NtGdiDdDDIGetPresentHistory",
"NtGdiDdDDIGetPresentQueueEvent",
"NtGdiDdDDIGetProcessSchedulingPriorityClass",
"NtGdiDdDDIGetRuntimeData",
"NtGdiDdDDIGetScanLine",
"NtGdiDdDDIGetSharedPrimaryHandle",
"NtGdiDdDDIInvalidateActiveVidPn",
"NtGdiDdDDILock",
"NtGdiDdDDIOpenAdapterFromDeviceName",
"NtGdiDdDDIOpenAdapterFromHdc",
"NtGdiDdDDIOpenKeyedMutex",
"NtGdiDdDDIOpenResource",
"NtGdiDdDDIOpenSynchronizationObject",
"NtGdiDdDDIPollDisplayChildren",
"NtGdiDdDDIPresent",
"NtGdiDdDDIQueryAdapterInfo",
"NtGdiDdDDIQueryAllocationResidency",
"NtGdiDdDDIQueryResourceInfo",
"NtGdiDdDDIQueryStatistics",
"NtGdiDdDDIReleaseKeyedMutex",
"NtGdiDdDDIReleaseProcessVidPnSourceOwners",
"NtGdiDdDDIRender",
"NtGdiDdDDISetAllocationPriority",
"NtGdiDdDDISetContextSchedulingPriority",
"NtGdiDdDDISetDisplayMode",
"NtGdiDdDDISetDisplayPrivateDriverFormat",
"NtGdiDdDDISetGammaRamp",
"NtGdiDdDDISetProcessSchedulingPriorityClass",
"NtGdiDdDDISetQueuedLimit",
"NtGdiDdDDISetVidPnSourceOwner",
"NtGdiDdDDISharedPrimaryLockNotification",
"NtGdiDdDDISharedPrimaryUnLockNotification",
"NtGdiDdDDISignalSynchronizationObject",
"NtGdiDdDDIUnlock",
"NtGdiDdDDIUpdateOverlay",
"NtGdiDdDDIWaitForIdle",
"NtGdiDdDDIWaitForSynchronizationObject",
"NtGdiDdDDIWaitForVerticalBlankEvent",
"NtGdiDdDeleteDirectDrawObject",
"NtGdiDdDestroyD3DBuffer",
"NtGdiDdDestroyFullscreenSprite",
"NtGdiDdDestroyMoComp",
"NtGdiDdEndMoCompFrame",
"NtGdiDdFlip",
"NtGdiDdFlipToGDISurface",
"NtGdiDdGetAvailDriverMemory",
"NtGdiDdGetBltStatus",
"NtGdiDdGetDC",
"NtGdiDdGetDriverInfo",
"NtGdiDdGetDriverState",
"NtGdiDdGetDxHandle",
"NtGdiDdGetFlipStatus",
"NtGdiDdGetInternalMoCompInfo",
"NtGdiDdGetMoCompBuffInfo",
"NtGdiDdGetMoCompFormats",
"NtGdiDdGetMoCompGuids",
"NtGdiDdGetScanLine",
"NtGdiDdLock",
"NtGdiDdNotifyFullscreenSpriteUpdate",
"NtGdiDdQueryDirectDrawObject",
"NtGdiDdQueryMoCompStatus",
"NtGdiDdQueryVisRgnUniqueness",
"NtGdiDdReenableDirectDrawObject",
"NtGdiDdReleaseDC",
"NtGdiDdRenderMoComp",
"NtGdiDdSetColorKey",
"NtGdiDdSetExclusiveMode",
"NtGdiDdSetGammaRamp",
"NtGdiDdSetOverlayPosition",
"NtGdiDdUnattachSurface",
"NtGdiDdUnlock",
"NtGdiDdUpdateOverlay",
"NtGdiDdWaitForVerticalBlank",
"NtGdiDeleteColorTransform",
"NtGdiDescribePixelFormat",
"NtGdiDestroyOPMProtectedOutput",
"NtGdiDestroyPhysicalMonitor",
"NtGdiDoBanding",
"NtGdiDrawEscape",
"NtGdiDvpAcquireNotification",
"NtGdiDvpCanCreateVideoPort",
"NtGdiDvpColorControl",
"NtGdiDvpCreateVideoPort",
"NtGdiDvpDestroyVideoPort",
"NtGdiDvpFlipVideoPort",
"NtGdiDvpGetVideoPortBandwidth",
"NtGdiDvpGetVideoPortConnectInfo",
"NtGdiDvpGetVideoPortField",
"NtGdiDvpGetVideoPortFlipStatus",
"NtGdiDvpGetVideoPortInputFormats",
"NtGdiDvpGetVideoPortLine",
"NtGdiDvpGetVideoPortOutputFormats",
"NtGdiDvpGetVideoSignalStatus",
"NtGdiDvpReleaseNotification",
"NtGdiDvpUpdateVideoPort",
"NtGdiDvpWaitForVideoPortSync",
"NtGdiDxgGenericThunk",
"NtGdiEllipse",
"NtGdiEnableEudc",
"NtGdiEndDoc",
"NtGdiEndGdiRendering",
"NtGdiEndPage",
"NtGdiEngAlphaBlend",
"NtGdiEngAssociateSurface",
"NtGdiEngBitBlt",
"NtGdiEngCheckAbort",
"NtGdiEngComputeGlyphSet",
"NtGdiEngCopyBits",
"NtGdiEngCreateBitmap",
"NtGdiEngCreateClip",
"NtGdiEngCreateDeviceBitmap",
"NtGdiEngCreateDeviceSurface",
"NtGdiEngCreatePalette",
"NtGdiEngDeleteClip",
"NtGdiEngDeletePalette",
"NtGdiEngDeletePath",
"NtGdiEngDeleteSurface",
"NtGdiEngEraseSurface",
"NtGdiEngFillPath",
"NtGdiEngGradientFill",
"NtGdiEngLineTo",
"NtGdiEngLockSurface",
"NtGdiEngMarkBandingSurface",
"NtGdiEngPaint",
"NtGdiEngPlgBlt",
"NtGdiEngStretchBlt",
"NtGdiEngStretchBltROP",
"NtGdiEngStrokeAndFillPath",
"NtGdiEngStrokePath",
"NtGdiEngTextOut",
"NtGdiEngTransparentBlt",
"NtGdiEngUnlockSurface",
"NtGdiEnumFonts",
"NtGdiEnumObjects",
"NtGdiEudcLoadUnloadLink",
"NtGdiExtFloodFill",
"NtGdiFONTOBJ_cGetAllGlyphHandles",
"NtGdiFONTOBJ_cGetGlyphs",
"NtGdiFONTOBJ_pQueryGlyphAttrs",
"NtGdiFONTOBJ_pfdg",
"NtGdiFONTOBJ_pifi",
"NtGdiFONTOBJ_pvTrueTypeFontFile",
"NtGdiFONTOBJ_pxoGetXform",
"NtGdiFONTOBJ_vGetInfo",
"NtGdiFlattenPath",
"NtGdiFontIsLinked",
"NtGdiForceUFIMapping",
"NtGdiFrameRgn",
"NtGdiFullscreenControl",
"NtGdiGetBoundsRect",
"NtGdiGetCOPPCompatibleOPMInformation",
"NtGdiGetCertificate",
"NtGdiGetCertificateSize",
"NtGdiGetCharABCWidthsW",
"NtGdiGetCharacterPlacementW",
"NtGdiGetColorAdjustment",
"NtGdiGetColorSpaceforBitmap",
"NtGdiGetDeviceCaps",
"NtGdiGetDeviceCapsAll",
"NtGdiGetDeviceGammaRamp",
"NtGdiGetDeviceWidth",
"NtGdiGetDhpdev",
"NtGdiGetETM",
"NtGdiGetEmbUFI",
"NtGdiGetEmbedFonts",
"NtGdiGetEudcTimeStampEx",
"NtGdiGetFontFileData",
"NtGdiGetFontFileInfo",
"NtGdiGetFontResourceInfoInternalW",
"NtGdiGetFontUnicodeRanges",
"NtGdiGetGlyphIndicesW",
"NtGdiGetGlyphIndicesWInternal",
"NtGdiGetGlyphOutline",
"NtGdiGetKerningPairs",
"NtGdiGetLinkedUFIs",
"NtGdiGetMiterLimit",
"NtGdiGetMonitorID",
"NtGdiGetNumberOfPhysicalMonitors",
"NtGdiGetOPMInformation",
"NtGdiGetOPMRandomNumber",
"NtGdiGetObjectBitmapHandle",
"NtGdiGetPath",
"NtGdiGetPerBandInfo",
"NtGdiGetPhysicalMonitorDescription",
"NtGdiGetPhysicalMonitors",
"NtGdiGetRealizationInfo",
"NtGdiGetServerMetaFileBits",
"DxgStubAlphaBlt",
"NtGdiGetStats",
"NtGdiGetStringBitmapW",
"NtGdiGetSuggestedOPMProtectedOutputArraySize",
"NtGdiGetTextExtentExW",
"NtGdiGetUFI",
"NtGdiGetUFIPathname",
"NtGdiGradientFill",
"NtGdiHLSurfGetInformation",
"NtGdiHLSurfSetInformation",
"NtGdiHT_Get8BPPFormatPalette",
"NtGdiHT_Get8BPPMaskPalette",
"NtGdiIcmBrushInfo",
"EngRestoreFloatingPointState",
"NtGdiInitSpool",
"NtGdiMakeFontDir",
"NtGdiMakeInfoDC",
"NtGdiMakeObjectUnXferable",
"NtGdiMakeObjectXferable",
"NtGdiMirrorWindowOrg",
"NtGdiMonoBitmap",
"NtGdiMoveTo",
"NtGdiOffsetClipRgn",
"NtGdiPATHOBJ_bEnum",
"NtGdiPATHOBJ_bEnumClipLines",
"NtGdiPATHOBJ_vEnumStart",
"NtGdiPATHOBJ_vEnumStartClipLines",
"NtGdiPATHOBJ_vGetBounds",
"NtGdiPathToRegion",
"NtGdiPlgBlt",
"NtGdiPolyDraw",
"NtGdiPolyTextOutW",
"NtGdiPtInRegion",
"NtGdiPtVisible",
"NtGdiQueryFonts",
"NtGdiRemoveFontResourceW",
"NtGdiRemoveMergeFont",
"NtGdiResetDC",
"NtGdiResizePalette",
"NtGdiRoundRect",
"NtGdiSTROBJ_bEnum",
"NtGdiSTROBJ_bEnumPositionsOnly",
"NtGdiSTROBJ_bGetAdvanceWidths",
"NtGdiSTROBJ_dwGetCodePage",
"NtGdiSTROBJ_vEnumStart",
"NtGdiScaleViewportExtEx",
"NtGdiScaleWindowExtEx",
"NtGdiSelectBrush",
"NtGdiSelectClipPath",
"NtGdiSelectPen",
"NtGdiSetBitmapAttributes",
"NtGdiSetBrushAttributes",
"NtGdiSetColorAdjustment",
"NtGdiSetColorSpace",
"NtGdiSetDeviceGammaRamp",
"NtGdiSetFontXform",
"NtGdiSetIcmMode",
"NtGdiSetLinkedUFIs",
"NtGdiSetMagicColors",
"NtGdiSetOPMSigningKeyAndSequenceNumbers",
"NtGdiSetPUMPDOBJ",
"NtGdiSetPixelFormat",
"NtGdiSetRectRgn",
"NtGdiSetSizeDevice",
"NtGdiSetSystemPaletteUse",
"NtGdiSetTextJustification",
"NtGdiSfmGetNotificationTokens",
"NtGdiStartDoc",
"NtGdiStartPage",
"NtGdiStrokeAndFillPath",
"NtGdiStrokePath",
"NtGdiSwapBuffers",
"NtGdiTransparentBlt",
"NtGdiUMPDEngFreeUserMem",
"DxgStubAlphaBlt",
"EngRestoreFloatingPointState",
"NtGdiUpdateColors",
"NtGdiUpdateTransform",
"NtGdiWidenPath",
"NtGdiXFORMOBJ_bApplyXform",
"NtGdiXFORMOBJ_iGetXform",
"NtGdiXLATEOBJ_cGetPalette",
"NtGdiXLATEOBJ_hGetColorTransform",
"NtGdiXLATEOBJ_iXlate",
"NtUserAddClipboardFormatListener",
"NtUserAssociateInputContext",
"NtUserBlockInput",
"NtUserBuildHimcList",
"NtUserBuildPropList",
"NtUserCalculatePopupWindowPosition",
"NtUserCallHwndOpt",
"NtUserChangeDisplaySettings",
"NtUserChangeWindowMessageFilterEx",
"NtUserCheckAccessForIntegrityLevel",
"NtUserCheckDesktopByThreadId",
"NtUserCheckWindowThreadDesktop",
"NtUserChildWindowFromPointEx",
"NtUserClipCursor",
"NtUserCreateDesktopEx",
"NtUserCreateInputContext",
"NtUserCreateWindowStation",
"NtUserCtxDisplayIOCtl",
"NtUserDestroyInputContext",
"NtUserDisableThreadIme",
"NtUserDisplayConfigGetDeviceInfo",
"NtUserDisplayConfigSetDeviceInfo",
"NtUserDoSoundConnect",
"NtUserDoSoundDisconnect",
"NtUserDragDetect",
"NtUserDragObject",
"NtUserDrawAnimatedRects",
"NtUserDrawCaption",
"NtUserDrawCaptionTemp",
"NtUserDrawMenuBarTemp",
"NtUserDwmStartRedirection",
"NtUserDwmStopRedirection",
"NtUserEndMenu",
"NtUserEndTouchOperation",
"NtUserEvent",
"NtUserFlashWindowEx",
"NtUserFrostCrashedWindow",
"NtUserGetAppImeLevel",
"NtUserGetCaretPos",
"NtUserGetClipCursor",
"NtUserGetClipboardViewer",
"NtUserGetComboBoxInfo",
"NtUserGetCursorInfo",
"NtUserGetDisplayConfigBufferSizes",
"NtUserGetGestureConfig",
"NtUserGetGestureExtArgs",
"NtUserGetGestureInfo",
"NtUserGetGuiResources",
"NtUserGetImeHotKey",
"NtUserGetImeInfoEx",
"NtUserGetInputLocaleInfo",
"NtUserGetInternalWindowPos",
"NtUserGetKeyNameText",
"NtUserGetKeyboardLayoutName",
"NtUserGetLayeredWindowAttributes",
"NtUserGetListBoxInfo",
"NtUserGetMenuIndex",
"NtUserGetMenuItemRect",
"NtUserGetMouseMovePointsEx",
"NtUserGetPriorityClipboardFormat",
"NtUserGetRawInputBuffer",
"NtUserGetRawInputData",
"NtUserGetRawInputDeviceInfo",
"NtUserGetRawInputDeviceList",
"NtUserGetRegisteredRawInputDevices",
"NtUserGetTopLevelWindow",
"NtUserGetTouchInputInfo",
"NtUserGetUpdatedClipboardFormats",
"NtUserGetWOWClass",
"NtUserGetWindowCompositionAttribute",
"NtUserGetWindowCompositionInfo",
"NtUserGetWindowDisplayAffinity",
"NtUserGetWindowMinimizeRect",
"NtUserGetWindowRgnEx",
"NtUserGhostWindowFromHungWindow",
"NtUserHardErrorControl",
"NtUserHiliteMenuItem",
"NtUserHungWindowFromGhostWindow",
"NtUserHwndQueryRedirectionInfo",
"NtUserHwndSetRedirectionInfo",
"NtUserImpersonateDdeClientWindow",
"NtUserInitTask",
"NtUserInitialize",
"NtUserInitializeClientPfnArrays",
"NtUserInjectGesture",
"NtUserInternalGetWindowIcon",
"NtUserIsTopLevelWindow",
"NtUserIsTouchWindow",
"NtUserLoadKeyboardLayoutEx",
"NtUserLockWindowStation",
"NtUserLockWorkStation",
"NtUserLogicalToPhysicalPoint",
"NtUserMNDragLeave",
"NtUserMNDragOver",
"NtUserMagControl",
"NtUserMagGetContextInformation",
"NtUserMagSetContextInformation",
"NtUserManageGestureHandlerWindow",
"NtUserMenuItemFromPoint",
"NtUserMinMaximize",
"NtUserModifyWindowTouchCapability",
"NtUserNotifyIMEStatus",
"NtUserOpenInputDesktop",
"NtUserOpenThreadDesktop",
"NtUserPaintMonitor",
"NtUserPhysicalToLogicalPoint",
"NtUserPrintWindow",
"NtUserQueryDisplayConfig",
"NtUserQueryInformationThread",
"NtUserQueryInputContext",
"NtUserQuerySendMessage",
"NtUserRealChildWindowFromPoint",
"NtUserRealWaitMessageEx",
"NtUserRegisterErrorReportingDialog",
"NtUserRegisterHotKey",
"NtUserRegisterRawInputDevices",
"NtUserRegisterServicesProcess",
"NtUserRegisterSessionPort",
"NtUserRegisterTasklist",
"NtUserRegisterUserApiHook",
"NtUserRemoteConnect",
"NtUserRemoteRedrawRectangle",
"NtUserRemoteRedrawScreen",
"NtUserRemoteStopScreenUpdates",
"NtUserRemoveClipboardFormatListener",
"NtUserResolveDesktopForWOW",
"NtUserSendTouchInput",
"NtUserSetAppImeLevel",
"NtUserSetChildWindowNoActivate",
"NtUserSetClassWord",
"NtUserSetCursorContents",
"NtUserSetDisplayConfig",
"NtUserSetGestureConfig",
"NtUserSetImeHotKey",
"NtUserSetImeInfoEx",
"NtUserSetImeOwnerWindow",
"NtUserSetInternalWindowPos",
"NtUserSetLayeredWindowAttributes",
"NtUserSetMenu",
"NtUserSetMenuContextHelpId",
"NtUserSetMenuFlagRtoL",
"NtUserSetMirrorRendering",
"NtUserSetObjectInformation",
"NtUserSetProcessDPIAware",
"NtUserSetShellWindowEx",
"NtUserSetSysColors",
"NtUserSetSystemCursor",
"NtUserSetSystemTimer",
"NtUserSetThreadLayoutHandles",
"NtUserSetWindowCompositionAttribute",
"NtUserSetWindowDisplayAffinity",
"NtUserSetWindowRgnEx",
"NtUserSetWindowStationUser",
"NtUserSfmDestroyLogicalSurfaceBinding",
"NtUserSfmDxBindSwapChain",
"NtUserSfmDxGetSwapChainStats",
"NtUserSfmDxOpenSwapChain",
"NtUserSfmDxQuerySwapChainBindingStatus",
"NtUserSfmDxReleaseSwapChain",
"NtUserSfmDxReportPendingBindingsToDwm",
"NtUserSfmDxSetSwapChainBindingStatus",
"NtUserSfmDxSetSwapChainStats",
"NtUserSfmGetLogicalSurfaceBinding",
"NtUserShowSystemCursor",
"NtUserSoundSentry",
"NtUserSwitchDesktop",
"NtUserTestForInteractiveUser",
"NtUserTrackPopupMenuEx",
"NtUserUnloadKeyboardLayout",
"NtUserUnlockWindowStation",
"NtUserUnregisterHotKey",
"NtUserUnregisterSessionPort",
"NtUserUnregisterUserApiHook",
"NtUserUpdateInputContext",
"NtUserUpdateInstance",
"NtUserUpdateLayeredWindow",
"NtUserUpdatePerUserSystemParameters",
"NtUserUpdateWindowTransform",
"NtUserUserHandleGrantAccess",
"NtUserValidateHandleSecure",
"NtUserWaitForInputIdle",
"NtUserWaitForMsgAndEvent",
"NtUserWindowFromPhysicalPoint",
"NtUserYieldTask",
"NtUserSetClassLongPtr",
"NtUserSetWindowLongPtr"

};
